- name: Removing Jenkins
  apt:
    name: jenkins
    state: absent
    autoremove: yes
    purge: yes

- name: Removing Java
  apt:
    name: openjdk-11-jdk
    state: absent
    autoremove: yes
    purge: yes

- name: Removing apt repo key
  apt_key:
    id: 45F2C3D5
    state: absent

- name: Removing Nginx
  apt:
    name: nginx
    state: absent
    autoremove: yes
    purge: yes

