- name: changing sysctl parameters
  sysctl:
    name: '{{ item.key }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    state: present
    ignoreerrors: yes
  with_dict: '{{ sysctl_config }}'

- name: add Jenkins apt repository key
  apt_key:
    url: "https://pkg.jenkins.io/debian-stable/jenkins.io.key"
    state: present

- name: add jenkins apt repository
  apt_repository:
    repo: "deb http://pkg.jenkins.io/debian-stable binary/"
    state: present
    update_cache: true
  
- name: installing openjdk-11-jdk
  apt:
    name: openjdk-11-jdk
    state: present

- name: installing jenkins
  apt:
    name: jenkins
    state: present
    update_cache: true

- name: changing jenkins port 8080-->8081
  lineinfile:
    path: /etc/default/jenkins
    regexp: "^HTTP_PORT=8080"
    line: HTTP_PORT=8081

- name: restart jenkins
  service:
    name: jenkins
    state: restarted
    enabled: yes

- name: create jenkins init scripts directory
  file:
    path: "{{ jenkins_home }}/init.groovy.d"
    state: directory
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0775

- name: copy plugins file
  copy:
    src: jenkins.yaml
    dest: "{{ jenkins_home }}"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0775
