- name: Changing sysctl parameters
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    state: present
    ignoreerrors: yes
  with_dict: "{{ sysctl_config }}"

- name: Adding Jenkins apt repository key
  apt_key:
    url: "{{ jenkins_repo_key }}"
    state: present

- name: Adding Jenkins apt repository
  apt_repository:
    repo: "{{ jenkins_repo }}"
    state: present
    update_cache: true
  
- name: Installing {{ openjdk_package }}
  apt:
    name: "{{ openjdk_package }}"
    state: present

- name: Installing Jenkins
  apt:
    name: jenkins
    state: present
 
- name: Installing Nginx
  apt:
    name: nginx
    state: present

- name: Changing Jenkins port from 8080 --> {{ jenkins_port }}
  lineinfile:
    path: "{{ jenkins_config }}"
    regexp: "^HTTP_PORT=8080"
    line: "HTTP_PORT={{ jenkins_port }}"

- name: Disabling Jenkins setup wizzard
  lineinfile:
    path: "{{ jenkins_config }}"
    regexp: '^#JAVA_ARGS="-Xmx256m"'
    line: "{{ java_args }}"

- name: Creating Jenkins init scripts directory
  file:
    path: "{{ jenkins_init_path }}"
    state: directory
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0775

- name: Copying init script to create a Jenkins user
  template: src=00-add-user.groovy.j2
            dest="{{ jenkins_init_path }}/00-add-user.groovy"

- name: Copying Nginx reverse proxy config file
  copy:
    src: default
    dest: "/etc/nginx/sites-available/"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0775

- name: Restarting Jenkins
  service:
    name: jenkins
    state: restarted
    enabled: yes

- name: Restarting Nginx
  service:
    name: nginx
    state: restarted
    enabled: yes

- name: Installing Jenkins plugins using password
  jenkins_plugin:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default(omit) }}"
    jenkins_home: "{{ jenkins_home }}"
    url_username: "{{ jenkins_admin_username }}"
    url_password: "{{ jenkins_admin_password }}"
    state: latest
    timeout: 10
    updates_expiration: 86400
    updates_url: "{{ jenkins_updates_url }}"
    url: "http://{{ jenkins_ip }}:{{ jenkins_port }}"
  with_items: "{{ jenkins_plugins }}"
  register: plugin_result
  until: plugin_result is success
  retries: 5
  delay: 2
 
- name: Restarting Jenkins
  service:
    name: jenkins
    state: restarted
    enabled: yes
