- name: changing sysctl parameters
  sysctl:
    name: '{{ item.key }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    state: present
    ignoreerrors: yes
  with_dict: '{{ sysctl_config }}'

- name: delete jenkins
  apt:
    name: jenkins
    state: absent
    purge: yes
    update_cache: yes

- name: updating repository cache
  apt:
    update_cache: yes

- name: add jenkins apt repository
  apt_repository:
    repo: "deb http://pkg.jenkins.io/debian-stable binary/"
    state: present
    update_cache: true

- name: add Jenkins apt repository key
  apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
    state: present

- name: updating repository cache
  apt:
    update_cache: yes
  
- name: installing openjdk-11-jdk
  apt:
    name: openjdk-11-jdk
    state: present

- name: installing jenkins
  apt:
    name: jenkins
    state: present

- name: daemon-reload
  systemd:
    daemon_reload: yes

- name: start jenkins
  systemd:
    name: jenkins
    state: started

- name: changing jenkins port 8080-->8081
  lineinfile:
    path: /etc/default/jenkins
    regexp: "^HTTP_PORT=8080"
    line: HTTP_PORT=8081
